version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'dependabot'
    groups:
      npm-all-dependencies:
        patterns:
          - '*' # npmエコシステムのすべての依存関係をこのグループに含めます
    # メジャーアップデートを無視する設定
    ignore:
      - dependency-name: '*' # すべての npm 依存関係に対して
        update-types: ['version-update:semver-major'] # メジャーアップデートを無視

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore(actions)'
      include: 'scope'
    labels:
      - 'github-actions'
      - 'dependabot'
    groups:
      github-actions-all:
        patterns:
          - '*' # GitHub Actionsエコシステムのすべての依存関係をこのグループに含めます
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
